name: Daily Top Articles

on:
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
    - run: |
         run install --allow-env --allow-net --allow-write -n most-popular-articles ./scripts/most-popular-articles.ts
         most-popular-articles
      env:
        CI: true
        DEV_TO_API_KEY: ${{ secrets.SuperSecret }}
