name: Daily Top Articles

on:
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Deno
      uses: denolib/deno-action@0.20.0
      with:
        args: run --allow-env --allow-net --allow-write ./scripts/most-popular-articles.ts
      env:
        CI: true
        DEV_TO_API_KEY: ${{ secrets.SuperSecret }}
