name: Daily Top Articles

on:
  schedule:
  - cron: 0 1 * * *
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x
    - name: Install
      run: |
         deno install --allow-env --allow-net --allow-write -n most-popular-articles ./scripts/most-popular-articles.ts
      env:
        CI: true
    - name: Run
      run: most-popular-articles
      env:
        DEV_TO_PUBLISHED: ${{ github.event_name == 'schedule' }}
        DEV_TO_API_KEY: ${{ secrets.DEV_TO_API_KEY }}

